/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDialog: typeof import('./src/components/common/AppDialog.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CreateServerForm: typeof import('./src/components/servers/create-join/CreateServerForm.vue')['default']
    EntityLogoHandling: typeof import('./src/components/common/EntityLogoHandling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JoinServerForm: typeof import('./src/components/servers/create-join/JoinServerForm.vue')['default']
    Members: typeof import('./src/components/servers/members/Members.vue')['default']
    MembersList: typeof import('./src/components/servers/members/MembersList.vue')['default']
    ProfileButton: typeof import('./src/components/ProfileButton.vue')['default']
    ProviderButton: typeof import('./src/components/auth/ProviderButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Server: typeof import('./src/components/servers/Server.vue')['default']
    ServerCreateJoinDialog: typeof import('./src/components/servers/create-join/ServerCreateJoinDialog.vue')['default']
    ServerListItems: typeof import('./src/components/servers/list/ServerListItems.vue')['default']
    ServersActionsList: typeof import('./src/components/servers/ServersActionsList.vue')['default']
    ServersList: typeof import('./src/components/servers/list/ServersList.vue')['default']
    Sidebar: typeof import('./src/components/asides/sidebar.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemeSelector: typeof import('./src/components/common/ThemeSelector.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Topbar: typeof import('./src/components/asides/topbar.vue')['default']
    TransitionWrapper: typeof import('./src/components/common/TransitionWrapper.vue')['default']
    UpdateModal: typeof import('./src/components/UpdateModal.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
