/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCreateDialog: typeof import('./src/components/activities/create/ActivityCreateDialog.vue')['default']
    ActivityCreateForm: typeof import('./src/components/activities/create/ActivityCreateForm.vue')['default']
    ActivityFilterBar: typeof import('./src/components/activities/ActivityFilterBar.vue')['default']
    ActivitySkillLevelsForm: typeof import('./src/components/activities/create/ActivitySkillLevelsForm.vue')['default']
    AppDialog: typeof import('./src/components/common/dialogs/AppDialog.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    AvatarButton: typeof import('./src/components/common/AvatarButton.vue')['default']
    Button: typeof import('primevue/button')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    ConfirmationDialog: typeof import('./src/components/common/dialogs/ConfirmationDialog.vue')['default']
    ContextActionMenu: typeof import('./src/components/common/ContextActionMenu.vue')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    CreateServerForm: typeof import('./src/components/servers/create-join/CreateServerForm.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EntityBannerHandling: typeof import('./src/components/common/EntityBannerHandling.vue')['default']
    EntityLogoHandling: typeof import('./src/components/common/EntityLogoHandling.vue')['default']
    InputDialog: typeof import('./src/components/common/dialogs/InputDialog.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JoinServerForm: typeof import('./src/components/servers/create-join/JoinServerForm.vue')['default']
    LanguageSelector: typeof import('./src/components/common/selectors/LanguageSelector.vue')['default']
    Member: typeof import('./src/components/members/Member.vue')['default']
    MembersAside: typeof import('./src/components/asides/MembersAside.vue')['default']
    MembersList: typeof import('./src/components/members/list/MembersList.vue')['default']
    MembersListItems: typeof import('./src/components/members/list/MembersListItems.vue')['default']
    MultistepsDialog: typeof import('./src/components/common/dialogs/MultistepsDialog.vue')['default']
    MultiStepsDialog: typeof import('./src/components/common/dialogs/MultiStepsDialog.vue')['default']
    ProfileButton: typeof import('./src/components/ProfileButton.vue')['default']
    ProviderButton: typeof import('./src/components/auth/ProviderButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Server: typeof import('./src/components/servers/Server.vue')['default']
    ServerCreateJoinDialog: typeof import('./src/components/servers/create-join/ServerCreateJoinDialog.vue')['default']
    ServersActionsList: typeof import('./src/components/servers/ServersActionsList.vue')['default']
    ServersAside: typeof import('./src/components/asides/ServersAside.vue')['default']
    ServersList: typeof import('./src/components/servers/list/ServersList.vue')['default']
    ServersListItems: typeof import('./src/components/servers/list/ServersListItems.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemeSelector: typeof import('./src/components/common/selectors/ThemeSelector.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TopAside: typeof import('./src/components/asides/TopAside.vue')['default']
    Topbar: typeof import('./src/components/asides/topbar.vue')['default']
    TransitionWrapper: typeof import('./src/components/common/TransitionWrapper.vue')['default']
    UpdateModal: typeof import('./src/components/UpdateModal.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
