/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDialog: typeof import('./src/components/common/AppDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CreateServerForm: typeof import('./src/components/server/CreateServerForm.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    ProfileButton: typeof import('./src/components/sidebar/profile-button.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProviderButton: typeof import('./src/components/auth/ProviderButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    ServerItem: typeof import('./src/components/sidebar/server-item.vue')['default']
    ServersList: typeof import('./src/components/sidebar/ServersList.vue')['default']
    ServersActions: typeof import('./src/components/sidebar/servers-actions.vue')['default']
    Sidebar: typeof import('./src/components/layout/sidebar.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Topbar: typeof import('./src/components/layout/topbar.vue')['default']
    UpdateModal: typeof import('./src/components/UpdateModal.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
